### PR TITLE
adding pause/resume functionality

### PR DESCRIPTION
**Pull request by MoathOthman**

### CODE REVIEW

**Comment by martinezdelariva** [comment]
Hi!

I've found a couple of issues:
- Animation does not work if Pause/Resume buttons are tapped first.
- Tap Resume while animating, end the animation, and after a while it starts again.

**Comment by MoathOthman** [comment]
Hi,
I fixed the issues ...

Thank you,

**Comment by martinezdelariva** [comment]
I'll merge it and do a little refactor to introduce a `pause` state

**Comment by MoathOthman** [comment]
Thank you ,
Hope it will be useful :+1:

**Pull request merged**
